### ISSUE TITLE
Translated docs should be part of the release proces

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-docs#102]
Danish documentation is 100% translated and I keep the Danish docs updated as it gets updated in the obsidian-docs repository.

It would be nice if my work also got released from time to time. Ideally as part of all new releases including insider builds but at least as part of public releases.

Another effect will be that the users have the most current documentation available :)

/Henrik :)

**Comment by ericaxu** [comment]
We will try to remember this for each release moving forward, thanks!
