### ISSUE TITLE
obsidian have xss

### ISSUE THREAD

**Issue by l1angfeng** [obsidianmd/obsidian-docs#114]
![image](https://user-images.githubusercontent.com/33654458/119117017-6721f100-ba5b-11eb-95fe-6110015d49cc.png)

**Comment by lishid** [comment]
Hi there, could you please reach out to me on Discord (Licat#1607) with steps to repro? Thank you!

**Comment by l1angfeng** [comment]
i don't hava discord. i hava telegram

**Comment by lishid** [comment]
I don't use Telegram but email is fine - support at obsidian.md
