### ISSUE TITLE
Spanish Translation in Progress

### ISSUE THREAD

**Issue by AsocPro** [obsidianmd/obsidian-docs#117]
This isn’t an issue directly but this felt like the most appropriate place to place this. I’m currently working on a full translation of the docs into Spanish. As I expect it to be something that takes a couple of weeks at my current pace I figured mentioning it here would be good just in case anyone else decided to do the same so we could work together instead of duplicating efforts. 

Just to be clear I’m not asking for help as I’m fine to go through it all myself but I just want to avoid submitting a PR just to find out someone was doing the exact same thing and instead of working together we end up stepping on each other’s toes. 

I am curious about the preferred way that I submit PR’s for this. I was planning on going through and doing a full translation and then submitting it in one PR all together. (The spanish branch on my fork will get updates as I go along) But if it is preferable to have multiple PRs with smaller chunks then I can do that. 

I was also thinking it would be nice to have a section  in the README to help track changes for languages that are fully translated. My thoughts on how this would work would be a section for each language that was completed and people could add that they have validated the language docs to be at parity with the English docs at a specific commit so I could periodically do a diff since that commit on the English doc changes folder and see what changes need to be ported to the language to keep the docs up to date.  Git tags was another way I thought this might be able to work but I figured a section in plain text is a lot easier to manage with PRs and metadata like who verified the docs and maybe a date or something could be useful. 
Is this a section that would be OK to add to the when I finish the translation or am I missing a complexity that would make this not work as well as I’m thinking?

**Comment by ericaxu** [comment]
> I was also thinking it would be nice to have a section in the README to help track changes for languages that are fully translated.

Yes, that would be nice; the translation repo has this.

My suggestion would be to start a draft PR and then work on it, so that it's visible to everyone. I don't think it can 100% guarantee having another person working on it at the same time, but if I were to translate, I would check the active PRs first.

I hope that helps!
