### ISSUE TITLE
Propose to create help-ru site

### ISSUE THREAD

**Issue by JxhnnyUt8h** [obsidianmd/obsidian-docs#125]
Hello, 
I propose to create site for Russian version of the Help (like https://publish.obsidian.md/help-ru).
Thanks.

**Comment by ericaxu** [comment]
Good idea! Will close issue when we publish to the site

**Comment by ericaxu** [comment]
Please see here: https://publish.obsidian.md/help-ru

Let me know if we should fix the name of the site (I used Google Translate). Thanks!

**Comment by JxhnnyUt8h** [comment]
Great!!! One thing, title must be fixed:

обсидиан русская помощь --> Obsidian Русская Справка

Thank you!!!
