### ISSUE TITLE
Help docs Usage Policy

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-docs#158]
Hi, Silver and other translators.

I'm planning to hold an online workshop with some Japanese users to warm up Japanese community. At the workshop or any other media such as Youtube video, I would like to use Japanese help docs to explain Obsidian usage and help docs itself, which is so huge. I don't know whether I can do it. I think I need a permission from you. So, please tell me about conditions or policies. I'll follow them. If this kind of thing is not allowed, I don't use.

Thanks.

**Comment by ericaxu** [comment]
Hi there, yes, you can totally use it. Best of luck with your workshop!

**Comment by yo-goto** [comment]
It's nice. Thank you☺️
