### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by starise** [obsidianmd/obsidian-docs#17]
I started working on Italian translation. I'll keep track of progress here.
In case someone would like to help, let me know to avoid double work 😉

- [x]  📁 [~~Advanced topics~~] Argomenti avanzati
- [x]  📁 [~~Attachments~~] Allegati
- [x]  📁 [~~Customization~~] Personalizzazione
- [x]  📁 [~~How to~~] Guide
- [x]  📁 [~~Licenses & add-on services~~] Licenze e servizi aggiuntivi
- [x]  📁 [~~Panes~~] Pannelli
- [x]  📁 [~~Plugins~~] Plugin
- [x]  [~~Accepted file formats.md~~] Formati di file accettati.md
- [x]  [~~Credits.md~~] Crediti.md
- [x]  [~~Index.md~~] Indice.md 
- [x]  Obsidian.md
- [x]  [~~Start here.md~~] Inizia qui.md

**Comment by ericaxu** [comment]
Wow, great work! Hope to publish the localized help as well as bundling them as soon as possible!
