### ISSUE TITLE
Fix Obsidian.md blur effect on Safari

### ISSUE THREAD

**Issue by eliyap** [obsidianmd/obsidian-docs#174]
Hi Obsidian Devs, I think it is the closest repo for website bug reports.

Opening obsidian.md on Chrome and Safari, note that the "frosted glass" blur effect is missing in Safari.

<img width="3001" alt="Screen Shot 2021-08-06 at 10 00 43 AM" src="https://user-images.githubusercontent.com/7846005/128546197-c25f9d69-e5a0-4496-a16c-08d13a36591d.png">

This is because the `backdrop-filter: blur(5px)` property is not supported in Webkit ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter)), but is available as 
> Implemented with the vendor prefix: -webkit-

When I edit the CSS on Safari to add `-webkit-backdrop-filter: blur(5px)`, it works as intended:

<img width="822" alt="Screen Shot 2021-08-06 at 10 03 01 AM" src="https://user-images.githubusercontent.com/7846005/128546479-53275d1d-83ac-4a73-8012-015e568c5e30.png">

Safari Version: macOS 15.0 Beta 1

**Comment by ericaxu** [comment]
Added (not live yet), thanks!
