### ISSUE TITLE
Document paragraph manipulation keyboard shortcuts

### ISSUE THREAD

**Issue by loopernow** [obsidianmd/obsidian-docs#185]
The following paragraph-manipulating shortcuts in Obsidian are quite handy but not documented, probably because they aren't editable, overlap with non-app-specific keyboard shortcuts, and are context-specific. It would be nice if they could be fit in the documentation somewhere, as they're very hard to discover otherwise (I found reference to them in a forum post):

- When the cursor is anywhere in a paragraph and if no text is currently selected, Ctrl/Cmd-C or Ctrl/Cmd-X will copy or cut the paragraph, respectively.

These shortcuts function similarly to "Delete paragraph."

==

Another forum poster, malecjan, recommended putting the documentation of this shortcut in a new doc section like:

# Reorganizing chapters, blocks, paragraphs, lines
...

### Moving current line/paragraph: 
... (add info about dragging)
To copy/cut the current paragraph, place the text cursor in the paragraph and press Ctrl/Cmd-C or Ctrl/Cmd-X while no text is selected.

**Comment by dandv** [comment]
See also #206.
