### ISSUE TITLE
Can the limitations of Templates variables be documented?

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-docs#201]
Porting a template from Jinja to the Obsidian Core Templates plugin, I got tripped up by Obsidian's more restrictive syntax.

In Jinja, template variables are conventional written with spaces, like `{{ title }}`, although they also work with `{{title}}`.

Obsidian does not recognise the variable unless the spaces are removed `{{title}}`.

I feel it would be helpful to document this Obsidian restriction/limitation, to help those migrating from other templating systems.

https://help.obsidian.md/Plugins/Templates

**Comment by claremacrae** [comment]
@ericaxu Hi, I would be happy to offer some text in a PR on this, if you are happy for this content to be added.

**Comment by ericaxu** [comment]
Sure, you can submit a PR and we'll review it.
