### ISSUE TITLE
Please consider adding a reference link and internal reference link examples to "format your notes.md"

### ISSUE THREAD

**Issue by IJeepIt** [obsidianmd/obsidian-docs#21]
Please consider adding a reference link and internal reference link examples to "format your notes.md"

For example:

```
[Obsidian][1]
[internal link example 1][2]
[internal link example 2][3]

[1]: http://www.obsidian.md
[2]: obsidian://open?path=D:%2FPATH%2FTO%2FFILE.md
[3]: obsidian://open?vault=MainVault&file=MyNote.md
```

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-docs/commit/75ad3cbb639a2ff412e7b8b980a0294bca36a553

Thanks for the suggestioN!
