### ISSUE TITLE
Error in displaying content

### ISSUE THREAD

**Issue by Zheka126** [obsidianmd/obsidian-docs#216]
The problem appered **_after using the embedded code_**  (backwards quotes).
As you can see, some area has appeared that covers the content. 

![image](https://user-images.githubusercontent.com/62949851/148699272-a24bcdb4-54cb-4bc3-9f97-815fdce3f556.png)

**Comment by ericaxu** [comment]
This is not a repo to report bugs on Obsidian itself but rather Obsidian documentation. Please go here instead: https://forum.obsidian.md/c/bug-reports/7

Gentle reminder to disable all community plugins, themes, and snippets before reporting a bug, thanks! Type "debug info" into command palette to learn more.
