### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-docs#22]
I'm trying to keep track of translation progress imitating Italian translation issue for my motivation😹 
As of 2020-12-02, the current state of the translation process is up-to-date.

- [x] 📁 [Advanced topics] 高度なトピック 8/8
	- [x] [Contributing to Obsidian] Obsidianへのコントリビュート.md
	- [x] [Deleting files] ファイルの削除.md
	- [x] [How Obsidian stores data]  Obsidianにおけるデータの保存.md
	- [x] [HTML sanitization] HTMLのサニタイズ.md
	- [x] [Insider builds] インサイダービルド.md
	- [x] [Third-party plugins]サードパーティプラグイン.md
	- [x] [Using obsidian URI] Obsidian URIの利用.md
	- [x] [YAML front matter] YAMLフロントマター.md
- [x] 📁 [Attachments] アタッチメント
	- [x] [Slides demo] スライドのデモ.md
- [x] 📁 [Customization] カスタマイズ 2/2
	- [x] [Appearance] 外観.md
	- [x] [Custom hotkeys] カスタムホットキー.md
- [x] 📁 [How to] ガイド 17/17
	- [x] [Basic note taking] 基本的なノートテイキング.md
	- [x] [Create notes] ノートを作成する.md
	- [x] [Embed files] ファイルを埋め込む.md
	- [x] [Folding] テキストの折りたたみ.md
	- [x] [Format your notes] ノートをフォーマットする.md
	- [x] [Importing data] データのインポート.md
	- [x] [Internal link] 内部リンク.md
	- [x] [Keyboard shortcuts]キーボードショートカット.md
	- [x] [Link to blocks] ブロックへのリンク.md
	- [x] [Preview and edit modes] プレビューモードと編集モード.md
	- [x] [Rename notes] ノートの名前を変更する
	- [x] [Settings] 設定.md
	- [x] [Working with backlinks] バックリンクの扱い
	- [x] [Working with multiple cursors] 複数カーソルの操作
	- [x] [Working with multiple notes] 複数のノートを使った作業.md
	- [x] [Working with multiple vaults] 複数の保管庫での作業
	- [x] [Working with tags] タグの操作
	- [x] [Add aliases to note] ノートにエイリアスを追加する.md
- [x] 📁 [Licenses & add-on services]ライセンスとアドオンサービス 4/4
	- [x] [Catalyst license] カタリストライセンス.md
	- [x] [Commercial license] 商用ライセンス.md
	- [x] Obsidian Publish
	- [x] Obsidian Unlimited
- [x] 📁 [Panes] ペイン 2/2
	- [x] [Linked pane] リンクされたペイン.md
	- [x] [Pane layout] ペインのレイアウト.md
- [x] 📁 [Plugins] 22/22
	- [x] [Audio recorder] オーディオレコーダー.md
	- [x] [Backlinks] バックリンク.md
	- [x] [Command palette] コマンドパレット.md
	- [x] [Custom CSS] カスタムCSS.md
	- [x] [Daily notes] デイリーノート.md
	- [x] [File explorer] ファイルエクスプローラー.md
	- [x] [Graph view] グラフビュー.md
	- [x] [List of plugins] プラグインリスト.md
	- [x] [Markdown format converter] 
	- [x] [Open in default app] デフォルトのアプリで開く.md
	- [x] [Outline] アウトライン.md
	- [x] [Page preview] ページプレビュー.md
	- [x] Publish
	- [x] [Quick switcher]
	- [x] [Random note] ランダムノート.md
	- [x] [Search] 検索.md
	- [x] [Slides] スライド.md
	- [x] [Starred notes] スター付きノート.md
	- [x] [Tag pane] タグペイン.md
	- [x] [Templates ] テンプレート.md
	- [x] [Word count] ワードカウント.md
	- [x] [Workspaces] ワークスペース.md
	- [x] [Zettelkasten prefixer] Zettelkastenプレフィクサー
- [x] [Accepted file formats.md] 利用可能なファイルフォーマット.md
- [x] [Credits.md] クレジット.md
- [x] [Index.md] インデックス.md
- [x] Obsidian.md
- [x] [Start here.md] ここからはじめる.md

**Comment by yo-goto** [comment]
#25

**Comment by ericaxu** [comment]
Great! Should I close this? ✌️

**Comment by yo-goto** [comment]
oh, I'll close this issue right now.

**Comment by yo-goto** [comment]
I'm going to catch up with the latest and update Japanese translation.
