### ISSUE TITLE
Editing on Version: 1.1.0 (38)

### ISSUE THREAD

**Issue by dvansoye** [obsidianmd/obsidian-docs#234]
Changes to editing have recently changed. I noticed that after the installation of version: 1.1.0 (38), the following differences were found.

1. If you select text, and then press the delete key, nothing happens. In the past when you select a text and hit the delete key, the text was deleted. The workaround for this is to select text and then cut it. But this is less efficient and different from most other programs. For example, using this webpage, I can select text and then press the delete key and the selected text is deleted.
2. If you press and hold the delete key, characters are deleted one at a time. In the past when you press and held the delete key, the text was deleted word by word. If you knew that three words needed be deleted, you could press and hold and just count the number of haptic pulses that you would feel and then release the delete key. Now, I need to press the delete key and wait a long time before the words are eliminated. Again, on this webpage, when I press and hold the delete key, words are deleted one by one.
3. Scrolling up (by swiping your finger down on the screen) shows large empty areas until all at once, the screen is filled once again with text. I suspect this is because that editing view has been improved to render the page WYSIWYG (which I love). The work around is to scroll up past where you want to view and then scroll down to the exact spot. 

I consider the above 3 behaviors "bugs." However they may have been intended changes. But they are making me way less efficient. Not just because it's different. But because it takes a lot longer. Note I do all of my data entry using my phone. I have and Android Pixel 6 Pro running Windows 12. I'm using Microsoft SwiftKey. I'm hoping that the three above behaviors we're just oversights that were missed after a code rewrite. If these two behaviors could be regressed, I would greatly appreciate it.

**Comment by WhiteNoiseDev** [comment]
This repository is not for bug reports. It's for the documentation.

Post here:
https://forum.obsidian.md/

**Comment by ericaxu** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
