### ISSUE TITLE
When line feed input, the input method will lose focus in ipados 14.8.

### ISSUE THREAD

**Issue by woodleejc** [obsidianmd/obsidian-docs#237]
For Chinese users, when using the input method, there will be problems at the line feed. The window of the input method will pop up and run to the top, and then it will get stuck.
for example，text in obsidian：

你好你好你好，你好你好你好【a】      （Line Break）

if i type something at 【a】 position on top，Especially some long phrases in Pinyin input method，If the input phrase is relatively long and there is a cross line, then the input method will lose focus, the input box will disappear, and then get stuck. Sometimes it is necessary to restart the app.

This problem has plagued me for a long time. Updating the app can't solve it, so that I now paste it into the software after entering text in the memo.
I recorded a video at bottom. 

Thx, I like Obsidian very much.

—-

![B9BB072F-9091-4DE0-9818-DF4E52AC0695](https://user-images.githubusercontent.com/61342257/159403145-b06ccea0-b10e-4160-a4f4-f17e633939fd.png)

https://user-images.githubusercontent.com/61342257/159403160-f08d0c12-e348-407a-a52e-927f4dc143ff.MP4

**Comment by joethei** [comment]
This repository is for the documentation of Obsidian.
Bugs are filled over on the forum: <https://forum.obsidian.md/>
