### ISSUE TITLE
Could docs be added or made visible for Slash Commands core plugin?

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-docs#248]
From maintaining the hub's links to docs on core plugins, I noticed that:

1. This URL does not work:2. 
https://help.obsidian.md/Plugins/Slash+commands

2. Slash commands is not in the list of core plugins: 
![image](https://user-images.githubusercontent.com/4840096/166316520-a1e7f34c-4356-41bf-8802-575f866acd9d.png)

Yet weirdly, it did exist at some point:
https://github.com/obsidianmd/obsidian-docs/pull/242/files

**Comment by claremacrae** [comment]
https://help.obsidian.md/Plugins/Core+plugins has this, showing the broken link:

![image](https://user-images.githubusercontent.com/4840096/166316884-6c93c930-7b3e-4436-a722-c83a8b689518.png)

It's not a "missing Publish=True"-type case, is it?

**Comment by joethei** [comment]
As this is now available & visible in the published version I am closing this issue.
