### ISSUE TITLE
An issue when creating three backticks with asp.net

### ISSUE THREAD

**Issue by 7heKnight** [obsidianmd/obsidian-docs#254]
for an example:
![image](https://user-images.githubusercontent.com/60308445/169449870-55253b83-fed1-4a64-b6a0-933648077342.png)

![image](https://user-images.githubusercontent.com/60308445/169449787-14fdc770-8cd1-499a-b7f9-aa232fa4f4ed.png)

**Comment by ericaxu** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
