### ISSUE TITLE
Translation of Obsidian's plugin documentation

### ISSUE THREAD

**Issue by luhaifeng666** [obsidianmd/obsidian-docs#255]
Hi!
I have translated the [documentation](https://github.com/marcusolsson/obsidian-plugin-docs) of Obsidian's plugin to Chinese and this is my [repo](https://github.com/luhaifeng666/obsidian-plugin-docs-zh).
I hope that helps~ 😃

**Comment by ericaxu** [comment]
Great work! Maybe you can add a link to your work here?

https://github.com/obsidianmd/obsidian-docs/blob/master/zh/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95/%E7%AC%AC%E4%B8%89%E6%96%B9%E6%8F%92%E4%BB%B6.md

**Comment by luhaifeng666** [comment]
> Great work! Maybe you can add a link to your work here?
> 
> https://github.com/obsidianmd/obsidian-docs/blob/master/zh/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95/%E7%AC%AC%E4%B8%89%E6%96%B9%E6%8F%92%E4%BB%B6.md

I'm glad to hear that~Here is the [PR](https://github.com/obsidianmd/obsidian-docs/pull/256).

**Comment by luhaifeng666** [comment]
Some people have raised the issue of incomplete documentation, so I have added a comment module for the developers to discuss and improve the documentation.

**Comment by luhaifeng666** [comment]
Version 2.0 documents are being translated.

**Comment by luhaifeng666** [comment]
[V2.0](https://luhaifeng666.github.io/obsidian-plugin-docs-zh/zh2.0/) translation completed.

**Comment by ericaxu** [comment]
Should we close this issue or is it still useful to you?
