### ISSUE TITLE
tables in format your notes

### ISSUE THREAD

**Issue by Sheldontao** [obsidianmd/obsidian-docs#266]
tables need |(pipe) at the start of a line,  and separated by minus-(not hyphen–,option minus in Mac)

**Comment by ericaxu** [comment]
Can you be more clear about which doc needs updating and how?

Feel free to quote the original doc if that helps.

**Comment by Sheldontao** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/36765652/183232013-0783a234-1e4c-48c2-99c0-e1a949bc5bbc.png">
