### ISSUE TITLE
Go through Obsidian Publish refactor to recover lost sections

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-docs#268]
Some info including setting up Google Analytics were lost during this refactor: https://github.com/obsidianmd/obsidian-docs/pull/203

Please try to recover them and put them in an appropriate place if possible.

**Comment by marcusolsson** [comment]
Other than the Google Analytics section, is there anything else you feel is missing in the current docs? I purposely left out the docs for features that are well documented inside Obsidian itself, such as "Disallow search engine indexing".

Static assets such as publish.css, publish.js, and favicons are now under [Customize your site](https://help.obsidian.md/Obsidian+Publish/Customize+your+site).

**Comment by ericaxu** [comment]
If you've already gone through the PR we can close this issue!

The missing part usually only comes up when a user asks about something and we can't find a link. I can open new issues when it does come up to make it actionable. Closing this, thanks!
