### ISSUE TITLE
Go through Obsidian Sync refactor to recover lost sections

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-docs#269]
Some info, including a disclaimer that Sync is not for backup purposes, were lost during this restructure: https://github.com/obsidianmd/obsidian-docs/pull/200

**Comment by marcusolsson** [comment]
I'm not sure I understand what was lost here. There's a dedicated page for using Sync with third party services (to backup).

https://help.obsidian.md/Obsidian+Sync/Obsidian+Sync+and+third-party+services

There's a link to the page on the Sync index page even: 

https://help.obsidian.md/Obsidian+Sync/Introduction+to+Obsidian+Sync

**Comment by joethei** [comment]
Nothing was lost per see.

The problems described there show up often enough in support that I think, we should make it more visible for those that actually open the docs.
Something like a quick disclaimer in the introduction should be enough; to not use third party services and that Sync is not a backup service.

Also, the workflow for setting up sync got changed completely, the old way still works, but there is a new, way quicker method from the vault switcher.

**Comment by ericaxu** [comment]
+1 to what @joethei said. Marcus is aware that the setup process has changed though; he'll work on that soon.

A gentle warning to turn off Dropbox/iCloud etc when setting up is good. Linking to the third party page from there would greatly help!

I'll open separate issues for them
