### ISSUE TITLE
Sync: update getting started with vault switcher

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-docs#275]
Related: https://github.com/obsidianmd/obsidian-docs/issues/269

**Comment by marcusolsson** [comment]
Looking at the vault switch setup for Obsidian Sync, it seems like the user can only connect to remote vault that have already been created.

Reviewing the Set up Obsidian Sync page, it seems like it's still relevant. Feels like this should be a separate guide?

**Comment by ericaxu** [comment]
Yeah, something along the lines of "Setting up Sync on a new device". What do you think?
