### ISSUE TITLE
Sync: Specifically talk about auto-wiping third party sync conflicts

### ISSUE THREAD

**Issue by lishid** [obsidianmd/obsidian-docs#276]
Sometimes people setup their vault in OneDrive before switching to Sync, and OneDrive (and also the other competitors) have this mode called "Files On-Demand" enabled by default. It causes the files to be deleted on disk and Sync to think they have been deleted.

Perhaps we should have a section in the third party sync page to talk about this scenario.

(And more broadly, maybe we need somewhere in the setup guide workflow to specifically instruct people to move their vault outside of their previous third party sync solution)

**Comment by marcusolsson** [comment]
Sounds like a good thing to add to [Obsidian Sync and third-party services](https://help.obsidian.md/Obsidian+Sync/Obsidian+Sync+and+third-party+services).

I assume the preferred solution is to disable Files On-Demand when possible, or is there anything else the user need to consider in this scenario?

**Comment by lishid** [comment]
Correct. Disabling Files On-Demand, and also a gentle reminder to only use it on at most one device, and use a local non-synced vault on other devices.
