### ISSUE TITLE
Suggestion: Showcase all the different (default) colours and icons for the Callouts

### ISSUE THREAD

**Issue by thibaultmol** [obsidianmd/obsidian-docs#285]
Each callout has a different icon and colour, would be nice to display those in the docs maybe. Just a suggestion

**Comment by claremacrae** [comment]
I agree! In the meantime, here's one I created for myself when callouts were first released...
(So I don't know if the list of types is still complete, and if the default styling is still correct...)

[Obsidian Callouts.md](https://github.com/obsidianmd/obsidian-docs/files/9500563/Obsidian.Callouts.md)

**Comment by claremacrae** [comment]
> I agree! In the meantime, here's one I created for myself when callouts were first released... (So I don't know if the list of types is still complete, and if the default styling is still correct...)
> 
> [Obsidian Callouts.md](https://github.com/obsidianmd/obsidian-docs/files/9500563/Obsidian.Callouts.md)

The CSS code in that file was only for my education, and not something I was suggesting for adding to obsidian docs.

**Comment by joethei** [comment]
Since #270 has been merged this is now available.
<https://help.obsidian.md/How+to/Use+callouts>

**Comment by thibaultmol** [comment]
Awesome, thx everyone!
