### ISSUE TITLE
Android version doesn't allow double tap spacebar for period

### ISSUE THREAD

**Issue by shadybraden** [obsidianmd/obsidian-docs#297]
Android 12
Gboard 11.8.04.446165824-release-arm64-v8a 85483822 
Obsidian 1.3.2

Normally, when typing in any text field on Android, double tapping the spacebar will replace the first of the spaces with a period. 
This is the case for all keyboards I use, not just Gboard.

**Comment by joethei** [comment]
Please fill bug reports on our forum, if one does not exist already.
https://forum.obsidian.md/c/bug-reports/7
