### ISSUE TITLE
Text selection issue (select with MD tags)

### ISSUE THREAD

**Issue by nikitasius** [obsidianmd/obsidian-docs#302]
Hi folks,
i have an md text here
![image](https://user-images.githubusercontent.com/3670331/195314334-d09da031-398d-4333-a9d6-45a486c88fbd.png)

when i simply select the `red` one, it select whole text including ` once i release the mouse button
![image](https://user-images.githubusercontent.com/3670331/195314489-1ff4527c-8662-4c48-acf5-51e835dc74ba.png)

Thats pretty annoying, cause to avoid it i need to click twice (1st is to render the md line and 2nd is to select the text i need).

**Comment by joethei** [comment]
Bug Reports and Feature Requests are collected over on the forum, not here.
<https://forum.obsidian.md>

**Comment by nikitasius** [comment]
> Bug Reports and Feature Requests are collected over on the forum, not here. https://forum.obsidian.md

damn thats sad

**Comment by nikitasius** [comment]
well for tracking purposes https://forum.obsidian.md/t/text-selection-issue/44823
