### ISSUE TITLE
Markdown internal link features and gotchas need documenting

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-docs#305]
Help is missing info about Markdown internal links:

- One can get autocomplete suggestions for Markdown internal links by typing the wiki syntax, which will become Markdown when complete. (I've seen multiple people recently who thought that using Markdown links meant going without autocompletion, because they understandably never thought to use the syntax that they'd turned off.)

- Whether the resulting Markdown links are automatically updated when notes are moved.

- Markdown links in general need to be URL encoded or have their paths wrapped in angle brackets, and autocompletion will do it for you. (Confusion caused by Markdown links that contain spaces is pretty common.)

**Comment by marcusolsson** [comment]
I'm revisiting the docs for internal links in #350. Feel free to review and add comments on anything I've missed.
