### ISSUE TITLE
Unable to drag window after update

### ISSUE THREAD

**Issue by Archer720** [obsidianmd/obsidian-docs#307]
I have just updated to V1, and everything is working perfectly at the moment, apart from not being able to drag and move the window, I can resize it using keyboard shortcuts and the mouse, but I am only able to move it using generic keyboard shortcuts (windows key and arrow keys), is anybody else experiencing this problem?
(computer running windows 11)

**Comment by joethei** [comment]
Update your theme & plugins, restart Obsidian.
If it still does not work, switch to the default theme and see if it works there.

Also, this is not the place to report issues, you can ask in our community instead: <https://obsidian.md/community>
