### ISSUE TITLE
Question: Is the hint in the README about "do not translate"  still valid

### ISSUE THREAD

**Issue by Swissbite** [obsidianmd/obsidian-docs#316]
The [Readme.md](https://github.com/obsidianmd/obsidian-docs/blob/master/README.md#-as-of-nov-30-2021-the-docs-are-currently-going-through-massive-changes-so-we-do-not-recommend-starting-or-updating-your-translations-at-the-moment) shouts that it is not recommended to start translations.

Is this still the case?

> ### ⚠ _As of Nov 30, 2021, the docs are currently going through massive changes, so we do not recommend starting or updating your translations at the moment._

**Comment by ericaxu** [comment]
> The [Readme.md](https://github.com/obsidianmd/obsidian-docs/blob/master/README.md#-as-of-nov-30-2021-the-docs-are-currently-going-through-massive-changes-so-we-do-not-recommend-starting-or-updating-your-translations-at-the-moment) shouts that it is not recommended to start translations.
> 
> Is this still the case?
> 
> > ### ⚠ _As of Nov 30, 2021, the docs are currently going through massive changes, so we do not recommend starting or updating your translations at the moment._

Yes, see the recent PRs by @marcusolsson : https://github.com/obsidianmd/obsidian-docs/pulls
