### ISSUE TITLE
Can't install snap

### ISSUE THREAD

**Issue by amandabee** [obsidianmd/obsidian-docs#322]
I'm having trouble installing the snap. I don't see Obsidian in the [Snapstore](https://snapcraft.io/search?q=obsidianmd) when I search for [obsidian](https://snapcraft.io/search?q=obsidian) or [obsidianmd](https://snapcraft.io/search?q=obsidianmd).

I tried to download the snap and install from there and I'm getting `error: cannot find signatures with metadata for snap "Installed/obsidian_1.0.3_amd64.snap"`

Is there somewhere I should be looking for more detailed information? The whole idea of snap is that I should just be able to install apps through it and keep them up to date, so I usually install through the snap store, and have never tried to troubleshoot snap errors before.

**Comment by joethei** [comment]
Please ask in our community: <https://obsidian.md/community>,
this repository is only for the documentation itself.

**Comment by amandabee** [comment]
Thank you. 

I did look for a link to a community space and did not find it. It might be helpful to incorporate a link to   https://obsidian.md/community in the getting started section.
