### ISSUE TITLE
Typos in Markdown documentation

### ISSUE THREAD

**Issue by Angroid** [obsidianmd/obsidian-docs#324]
Hello,
In the numbered lists section of the markdown formatting documentation, the markdown syntax only shows 1. in every line. The output shows the correct numbered list.

**Comment by marcusolsson** [comment]
Using only 1. is called [lazy numbering](https://google.github.io/styleguide/docguide/style.html#use-lazy-numbering-for-long-lists). In fact, you'll find that the numbers in an ordered list don't actually mean anything.

If I type a broken sequence:

```md
1. First
33. Second
789. Third
```

... it still shows up as 

1. First
33. Second
789. Third

We prefer lazy numbering in the docs to avoid having to update number sequences when moving things around.
