### ISSUE TITLE
Drag and drop image in excalidraw

### ISSUE THREAD

**Issue by OignonFrit** [obsidianmd/obsidian-docs#335]
Hello there,

Anyone knows why i when i drag and drop an image in excalidraw it shows me the website link instead of the image ?
It works when i copy paste it tho, but it should be better to just drag it's not handy with a stylus
Thanks in advance for your help !

**Comment by joethei** [comment]
Please ask either in our community (<https://obsidian.md/community>)
or on the repo of the excalidraw plugin (<https://github.com/zsviczian/obsidian-excalidraw-plugin>)

This repository is for our official documentation
