### ISSUE TITLE
Toggles are not displayed correctly

### ISSUE THREAD

**Issue by mklengel** [obsidianmd/obsidian-docs#336]
Obsidian 1.4.1 (83)
iPadOS 16.1.1
iPad Pro 10.5

See the screenshot, the toggles are not correctly aligned.
![05BD1029-AEBF-4F5C-A006-2B667814B626](https://user-images.githubusercontent.com/2345934/205915366-4981233a-c4b4-4db4-ac90-fab8159195e9.jpeg)

**Comment by joethei** [comment]
That looks like a theme issue.
Report it on the repo of your theme.

Also, this repository is not for reporting issues in the app itself.
We only accept reports on our forum.

**Comment by mklengel** [comment]
You are right. Changing the theme solves the problem. Thx for the solution.RegardsMichael„Don’t talk about nothing you know nothing about.“ John YoungAm 06.12.2022 um 15:00 schrieb Johannes Theiner ***@***.***>:﻿
That looks like a theme issue.
Report it on the repo of your theme.
Also, this repository is not for reporting issues in the app itself.
We only accept reports on our forum.
