### ISSUE TITLE
Obsidian Sync instructions should clearly state that a password is unique to the vault

### ISSUE THREAD

**Issue by chris-lesage** [obsidianmd/obsidian-docs#342]
At the moment the Obsidian Sync instructions imply that you are entering a password that already exists. There is already some confusion between Obsidian accounts, Sync vaults, and the Forum. I suggest some rephrasing to make it clear that you are choosing a new unique password for your Obsidian Sync vault.:

**Current:** In Encryption password, **enter the password** for your vault. This creates an end-to-end encrypted vault.

**New Suggestion**: In Encryption password, **choose a password for your vault**. This creates an end-to-end encrypted vault. This vault password is completely separate from your Obsidian account, and can be different for each vault you set up to sync.

**Comment by ericaxu** [comment]
Good point, thanks for the issue!
