### ISSUE TITLE
When is the good time to start new translation?

### ISSUE THREAD

**Issue by kunyu96** [obsidianmd/obsidian-docs#349]
In the [README.md](https://github.com/obsidianmd/obsidian-docs/blob/master/README.md), I noticed that:
> ⚠ As of Nov 30, 2021, the docs are currently going through massive changes, so we do not recommend starting or updating your translations at the moment.

However, there are some difference and inconsistentence in the Chinese version doc compared to the English doc now, like some newly added feature, i.e. Canvas. 

May I know when is appropriate to start translation the doc? @ericaxu

**Comment by marcusolsson** [comment]
Hi @kunyu96,

All documentation for Core plugins (including Canvas) is ready to be translated. No major docs changes for these are planned for the time being.

**Comment by ericaxu** [comment]
I updated the README as well. Thanks for asking @kunyu96 !
