### ISSUE TITLE
Update Title bar page

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-docs#366]
Users can now configure the title bar:

https://help.obsidian.md/User+interface/Workspace/Title+bar#Native+title+bar

**Comment by marcusolsson** [comment]
@ericaxu I'm considering removing the Title bar page altogether. The docs don't seem to add much other than explaining what the user can already see. Other than being able to change the frame style, what else would you say the user needs to know about the title bar?

**Comment by ericaxu** [comment]
> @ericaxu I'm considering removing the Title bar page altogether. The docs don't seem to add much other than explaining what the user can already see. Other than being able to change the frame style, what else would you say the user needs to know about the title bar?

Not really, I can't think of any!
