### ISSUE TITLE
"Open in a new tab group" shortcut is incorrect

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-docs#394]
On the "use tabs in Obsidian" section of help, (https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian#Open+a+new+tab+in+a+new+tab+group), the open in a new tab group shortcut is written as `Ctrl+Shift+t` (Windows). Shouldn't it be `Ctrl+Alt+Enter` or `Ctrl+Alt+Click`? Further down the page:

>To open and switch to a recently closed tab, press `Ctrl+Shift+t` (or `Cmd+Shift+t` on macOS).

works as expected. See forum post with more details: https://forum.obsidian.md/t/open-a-new-tab-in-a-new-tab-group/53542

**Comment by marcusolsson** [comment]
Hm. Not sure how this got added. AFAIK there's no way to open a new tab in a new tab group. Both of your alternative commands open a _note_ in a new tab group, which is different from opening a tab. Compare `Ctrl+N` vs `Ctrl+T`.

Thanks for reporting!

**Comment by trainbuffer** [comment]
Ahh, yes, `Ctrl+Alt+Click/Enter` opens a new note in a new tab group _not_ a blank tab, but you can see the confusion. Cheers!

**Comment by trainbuffer** [comment]
I see this was committed in #396 (thanks!) but the https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian hasn't changed yet. Are commits to the master done in batches or updating the public facing help page done at a different time?

**Comment by ericaxu** [comment]
> I see this was committed in #396 (thanks!) but the https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian hasn't changed yet. Are commits to the master done in batches or updating the public facing help page done at a different time?

Just published to the help site, is it fixed now?

**Comment by trainbuffer** [comment]
All good now!
