### ISSUE TITLE
🧟‍♀️ Zombie 404 hordes ransacking Google results

### ISSUE THREAD

**Issue by Leland** [obsidianmd/obsidian-docs#401]
![image](https://user-images.githubusercontent.com/714017/219483771-8ccc5467-fd7f-4ade-abd0-19d7b145fdae.png)

Hi there! You have apparently moved various URLs at some point in the past... but instead of redirecting them (good), or serving 404s (bad), there are zombie pages left that _say_ 404 but whose page title and response say contrary (ultra bad).

![image](https://user-images.githubusercontent.com/714017/219484278-afd25f33-0e35-4b7e-ab8b-5f592ebcc0cb.png)

In this case, https://help.obsidian.md/How+to/Use+callouts is getting served. Notice that the page says 404, but the response is a 200, and the page title happily chirps "Working with tags - Obsidian Help"

That means Google never drops these pages from their results, and they compete for space with the new ones (and frequently _win_, like in my case, due to age and backlinks).

I can also find others easily in Google's searches by searching for `site:https://help.obsidian.md/`, such as https://help.obsidian.md/How+to/Working+with+tags

----

Making these 404 properly would close this issue. But my recommendation is to take a catalogue of what URLs your documents used to have, and create redirects for all of them to their new homes (assuming analogues exist). It will do a lot for users clicking old links in blogs, and will help keep any SEO juice you currently have from these zombies.

**Comment by marcusolsson** [comment]
Thank you for the feedback! 👋 We're looking into a solution for this.
