### ISSUE TITLE
[mobile] New design isn't working as expected on mobile (iOS)

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-docs#412]
New design looks great! It works as expected on desktop and iPadOS, but mobile needs some love. 

https://youtube.com/shorts/YI7Wk4XEKkM

Environment:
iOS 16.3.1; iPhone13 pro; tested in Safari, Chrome, and Brave browsers

**Comment by ericaxu** [comment]
Thanks for reporting the Obsidian Publish bug! We'll take a look.

**Comment by liamcain** [comment]
Going to close this report now since we fixed the issue internally; we'll deploy the fix to Publish in the next couple days. Take care!

**Comment by trainbuffer** [comment]
Great!

Thanks for all the hard work everyone!
