### ISSUE TITLE
Sidebar <a> tags misroute users

### ISSUE THREAD

**Issue by BrendanRomanDev** [obsidianmd/obsidian-docs#431]
(_not that it matters, this seems like a routing issue)_
Chrome Version 111.0.5563.110 (Official Build) (arm64)

The collapse button works as expected, but **every item in the sidebar** where you'd expect that the obsidian docs would expand the list, it takes the user to https://obsidian.md/publish.

I recently started using obsidian and found this jarring while reading the docs, so I wanted to raise this issue.

https://user-images.githubusercontent.com/63918015/229302661-b1fb8336-38cc-4e7b-97b3-c7c4db5be3df.mov

**Comment by joethei** [comment]
Thanks for the report, fixed.
