### ISSUE TITLE
Online Doc for other language?

### ISSUE THREAD

**Issue by rosuH** [obsidianmd/obsidian-docs#64]
Hi, is there any online page for other languages? I've dug out some while in [publish.obsidian.md](https://publish.obsidian.md/help/Start+here) but found nothing. 🤔️
Or it just can read in this repo which would break obsidian's link.

Thanks for the works!

**Comment by ericaxu** [comment]
Good idea! We'll see what's the best way to set up the translated docs -- as a subfolder of the main help site or as separate sites. Right now it seems that using separate sites is better, so that the search results is cleaner.

I'll leave this issue open as a reminder, thanks for bringing this up!

**Comment by ericaxu** [comment]
Just set up some international help sites: 
https://publish.obsidian.md/help-da
https://publish.obsidian.md/help-it
https://publish.obsidian.md/help-zh
https://publish.obsidian.md/help-ja

Let me know by opening an issues if your language has complete docs that's ready to published too!
