### ISSUE TITLE
Main Source of Help files

### ISSUE THREAD

**Issue by JxhnnyUt8h** [obsidianmd/obsidian-docs#77]
Hi, the English Help has difference between GitHub's files and current Obsidian's application folder files.
Justy for example, descriprion of URI's Actions `new` and `hook-get-address` were missed in v0.11.10, in `Using obsidian URI.md` file.
Which version of the Help is recommended for translation? GitHub's files or Obsidian's local Help files?

Thanks!

**Comment by henrikfalk** [comment]
The GitHub files is the master files.
It seems that the newest help is not always included in new minor Obsidian releases.
It can take a few Obsidian versions before changes in GitHub are included in the application.

**Comment by JxhnnyUt8h** [comment]
Ok, roger that. Thank you for an answer.
