### ISSUE TITLE
Linux snap package is unsigned

### ISSUE THREAD

**Issue by traxeon** [obsidianmd/obsidian-docs#95]
When installing the snap package on Linux, error on install.  Unsigned package.

> sudo snap install obsidian_0.11.13_amd64.snap

error: cannot install "obsidian_0.11.13_amd64": invalid instance name: invalid instance key:
       "0.11.13_amd64"

WORKAROUND: 
> sudo snap install **--dangerous** obsidian_0.11.13_amd64.snap

OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.8.0-50-generic
Shell: bash 5.0.17
Resolution: 8768x2466
DE: GNOME 3.36.5
GTK Theme: Yaru-dark [GTK2/3]
Icon Theme: Yaru
CPU: Intel Core i7-8700K @ 12x 4.7GHz [50.0°C]
GPU: GeForce GTX 1080 Ti
RAM: 6978MiB / 64139MiB

**Comment by ericaxu** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
