### ISSUE TITLE
HiDPI settings not fully functioning on 4K monitors

### ISSUE THREAD

**Issue by traxeon** [obsidianmd/obsidian-docs#96]
Images and text for menus and the title bar are tiny on 4K monitors.  Other content seems fine.   Not sure if this is by design or a bug.

![image](https://user-images.githubusercontent.com/70642859/116496424-0562d280-a873-11eb-8d54-baa8f8317ed0.png)

**Comment by DanielSolmann** [comment]
+1

**Comment by ericaxu** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
